apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: custom-view-only-role
  namespace: develop
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - replicationcontrollers
  - replicationcontrollers/scale
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - delete
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: custom-view-only-rolebinding
  namespace: develop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: custom-view-only-role
subjects:
- kind: ServiceAccount
  name: develop
  namespace: default