apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-poi-deployment
  namespace:  pois
  labels:
    app: api-poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-poi
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
      labels:
        app: api-poi
    spec:
      containers:
        - image: <DOCKER_ID>/mongoApi
          imagePullPolicy: Always
          name: api-poi
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: api-poi-config
                  key: MONGO_URL
            - name: MONGO_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: api-poi-config
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: api-poi-config
                  key: MONGO_PASSWORD
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: api-poi-config
                  key: MONGO_DATABASE
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi