apiVersion: v1
kind: Pod
metadata:
  name: mongod-pod
  labels:
    name: mongodb
spec:
  containers:
  - name: mongodb
    image: mongo:4.0.8
    # set container for pull image on local
    #imagePullPolicy: Never
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: "root"
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: "root"
    # - name: MONGO_URL
    #   value: "localhost:27017"
    volumeMounts:
      - mountPath: "/data/db"
        name: my-mongo-volume
  volumes:
    - name: my-mongo-volume
      persistentVolumeClaim:
        claimName: mongo-pvc